TRUNCATE TABLE "CDA" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CDA_Pessoa" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "NaturezaDivida" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Pessoa" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PessoaFisica" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PessoaJuridica" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SituacaoCDA" RESTART IDENTITY CASCADE;